[package]
name = "imgmath"
version = "0.1.0"
description = "Run some math on images"
authors = ["Samuel Corsi-House <chouse.samuel@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
image = "0.24.7"
nalgebra-glm = "0.18.0"
